### ISSUE TITLE
AUBasePatient does not open in Forge

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#294]
AUBasePatient does not open in Forge. The other newly converted profiles open OK.

**Comment by RichardTON** [comment]
The Forge message is

2019-07-11T11:11:23
Forge Forge 22.0 for R4 - Redmond 2019 Edition
Version: Version 22.0.0.0 (ClickOnce)
FHIR Version: FHIR R4
--------------------------------------------------
FormatException in Hl7.Fhir.R4.Core:
Type checking the data: Since type BackboneElement is not a primitive, it cannot have a value (at StructureDefinition.context[0])
   at Hl7.Fhir.Serialization.ComplexTypeReader.Deserialize(ClassMapping mapping, Base existing)
   at Hl7.Fhir.Serialization.ResourceReader.Deserialize(Resource existing)
   at Hl7.Fhir.Serialization.PocoBuilder.<>c__DisplayClass8_0.<BuildFrom>g__build|0()
   at Hl7.Fhir.Serialization.PocoBuilder.BuildFrom(ITypedElement source)
   at Hl7.Fhir.Serialization.PocoBuilder.BuildFrom(ISourceNode source, String dataType)
   at Hl7.Fhir.Serialization.PocoBuilder.BuildFrom(ISourceNode source, Type dataType)
   at Hl7.Fhir.ElementModel.PocoBuilderExtensions.ToPoco[T](ISourceNode source, PocoBuilderSettings settings)
   at Hl7.Fhir.Specification.Source.DirectorySource.loadResourceInternal[T](ArtifactSummary summary)
   at Hl7.Fhir.Specification.Source.DirectorySource.ResolveByCanonicalUri(String uri)
   at Hl7.Fhir.Specification.Source.CachedResolver.InternalResolveByCanonicalUri(String url)
   at Hl7.Fhir.Specification.Source.CachedResolver.<.ctor>b__3_1(String id)
   at Hl7.Fhir.Specification.Source.CachedResolver.Cache`1.Get(String identifier, CachedResolverLoadingStrategy strategy)
   at Hl7.Fhir.Specification.Source.CachedResolver.ResolveByCanonicalUri(String url)
   at Hl7.Fhir.Specification.Source.MultiResolver.ResolveByCanonicalUri(String uri)
   at Forge.ViewModels.ProjectSource.ResolveByCanonicalUri(String uri)
   at Hl7.Fhir.Specification.Snapshot.SnapshotGenerator.mergeTypeProfiles(ElementDefinitionNavigator snap, ElementDefinitionNavigator diff)
   at Hl7.Fhir.Specification.Snapshot.SnapshotGenerator.mergeElement(ElementDefinitionNavigator snap, ElementDefinitionNavigator diff)
   at Hl7.Fhir.Specification.Snapshot.SnapshotGenerator.addSlice(ElementDefinitionNavigator snap, ElementDefinitionNavigator diff, ElementDefinitionNavigator sliceBase)
   at Hl7.Fhir.Specification.Snapshot.SnapshotGenerator.merge(ElementDefinitionNavigator snap, ElementDefinitionNavigator diff)
   at Hl7.Fhir.Specification.Snapshot.SnapshotGenerator.mergeElement(ElementDefinitionNavigator snap, ElementDefinitionNavigator diff)
   at Hl7.Fhir.Specification.Snapshot.SnapshotGenerator.merge(ElementDefinitionNavigator snap, ElementDefinitionNavigator diff)
   at Hl7.Fhir.Specification.Snapshot.SnapshotGenerator.generate(StructureDefinition structure)
   at Hl7.Fhir.Specification.Snapshot.SnapshotGenerator.Generate(StructureDefinition structure)
   at Forge.ViewModels.FhirSnapshots.expandAll(StructureDefinition structureDef, IResourceResolver resolver, Boolean useSnapshot)
   at Forge.ViewModels.StorageHandlerUtils.CreateStorageHandlers(IProfileVM target, String typeName)
   at Forge.ViewModels.ProfileVM.set_ModelElement(Base value)
   at Forge.ViewModels.ProfileVM.Initialize(Base modelElement, Base baseElement)
   at Forge.ViewModels.ProfileVM..ctor(ISessionNode owner, StructureDefinition model, StructureDefinition baseModel)
   at Forge.ViewModels.SessionItemVM.CreateResourceVM(ISessionFolder parentFolder, SessionItemVM owner, Resource model)
   at Forge.ViewModels.SessionItemVM..ctor(ISessionFolder owner, Resource model)
   at Forge.ViewModels.SessionFolderVM.Open(Resource model)
   at Forge.ViewModels.SessionDirectoryFolderVM.openArtifact(ArtifactSummaryVM summaryVM, Boolean asCopy)
   at Forge.ViewModels.SessionDirectoryFolderVM.Open(ArtifactSummaryVM summaryVM, Boolean asCopy)
   at Forge.ViewModels.SessionVM.<>c.<onDoubleClickDirectoryItem>b__311_0(SessionDirectoryFolderVM folder, ArtifactSummaryVM selItem)
   at Forge.ViewModels.SessionVM.<>c__DisplayClass239_0.<executeDirectoryItemCommand>b__0(SessionDirectoryFolderVM d, ArtifactSummaryVM i)
   at Forge.Common.UIServices.ExecuteOnUIThread[T1,T2](Action`2 action, T1 param1, T2 param2)
   at Forge.ViewModels.SessionVM.executeCommand[T1,T2](Action`2 action, T1 param1, T2 param2)

**Comment by vikasmittal-dh** [comment]
One reason can probably be because of the way "context" needs to be defined in STU3 vs R4.
STU3 - http://hl7.org/fhir/STU3/structuredefinition.html -- <contextType><context>
R4 - http://hl7.org/fhir/R4/structuredefinition.html -- <context> <context.type> <context.expression>

**Comment by oridashi** [comment]
should be fixed now

**Comment by vikasmittal-dh** [comment]
Yes it is now Brett. Thanks.
